[package]
name = "player"
version = "0.1.0"
authors = ["afourcat <alexandre.fourcat@epitech.eu>"]
edition = "2018"

[dependencies]
lightql = { git = "https://github.com/Afourcat/LightQl" }
serde = "*"
serde_derive = "*"
